### ISSUE TITLE
checkpoints and logs

### ISSUE THREAD

**Issue by songchuanle-1** [dfki-av/MiKASA-3DVG#2]
Hello, I am very interested in your work. Can you provide me with the training logs and weights? I would like to compare the results of my training

**Comment by birdy666** [comment]
Sorry for the late reply, pls find the [link](https://drive.google.com/drive/folders/1YB6nxjZwnBUyY_qQryjFTKKOhPmGUsFk?usp=sharing) here for the checkpoint.
I lost the log file but according to the note, Nr3D reached ~60% in 10 epochs and slowly reaching final score at ~epoch 99
Sr3D I dont remember.

**Comment by birdy666** [comment]
Thank you for your feedback. In the previous version, there was a testing script in the single_epoch_train function that trained the model for only 50 batches per epoch. This may have caused the training outcomes to be inconsistent with the checkpoints. Please either remove the script or pull the updated code. We sincerely apologize for any inconvenience caused and appreciate your understanding.
