### ISSUE TITLE
Error in loading

### ISSUE THREAD

**Issue by onmyoji-xiao** [dfki-av/MiKASA-3DVG#3]
There's an error when I test the provided "best_model.pth":
RuntimeError: Error(s) in loading state_dict for MiKASA_transformer:
        Unexpected key(s) in state_dict: "language_encoder.embeddings.position_ids".

**Comment by birdy666** [comment]
Hello,

Did you download the Bert pretrain? the best_model.pth does not contain the Bert pretrain, please download it first and modify the bert_pretrain_path
